server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: your_password
  dbname: slot_machine_db

redis:
  addr: localhost:6379
  password: ""
  db: 0

game:
  rtp: 0.96
  symbols:
    - "7"
    - "BAR"
    - "CHERRY"
    - "LEMON"
    - "ORANGE"